name: Blue Oaks Church
favicon: null
layout_spectrum: 0.9730185
typography_spectrum: 0.4907251
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.7403349
  lightness: 0.6382799
  saturation: 0.6875
  rhythmicContrast: 0.7676276
purpose: []
