layout_spectrum: 0.9730185
typography_spectrum: 0.4907251
color:
  lightness: 0.6382799
  brandStrength: 0.7403349
  saturation: 0.4494098
  rhythmicContrast: 0.7676276
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
name: Blue Oaks Church
